apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testjava0311
  janus-idp.io/tekton: testjava0311
  backstage.io/kubernetes-id: testjava0311
  backstage.io/kubernetes-namespace: testjava0311ns 
  app.kubernetes.io/part-of: testjava0311
resources: 
- deployment.yaml
- route.yaml
- service.yaml
