apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testjava0311
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testjava0311 
  name: testjava0311
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testjava0311 
